# Set up the Rust toolchain.
language: rust
rust:
  - stable
  - beta
  - nightly

# Since this build doesn't require sudo, we can turn it off and improve build
# performance.
sudo: false

cache: cargo

before_script:
  - export PATH="$PATH:$HOME/.cargo/bin"

# Generate documentation, compile the engine, run tests.
script: |
  cargo doc --all --no-deps -v &&
  cargo test --all -v
